### ISSUE TITLE
Update data in the spreadsheet from Typeform

### ISSUE THREAD

**Issue by arcanistzed** [HacktheHill/track-the-hack#1]

**Comment by Bricktech2000** [comment]
spreadsheet link **KEEP PRIVATE** <https://docs.google.com/spreadsheets/d/1YY9SZomhW-KvhS-m4B-rNxnH-KcBoRlkxT5P1PvL2sU/edit?usp=sharing>

**Comment by aydinyal** [comment]
Final rows from the exported typeform data were added to the google sheets file.
