### ISSUE TITLE
Allow organizers to view a hosted version of Prisma Studio

### ISSUE THREAD

**Issue by arcanistzed** [HacktheHill/track-the-hack#25]

**Comment by m9p909** [comment]
I was going to suggest that I do this, but we could probably just use the free tier of cloud.prisma.io

**Comment by m9p909** [comment]
seems like everything is assigned, if you need something done let me know.

**Comment by arcanistzed** [comment]
Yeah, I'm aware of Prisma Cloud and that's probably what we're going to use. I forgot to update this issue. Thank you.
