### ISSUE TITLE
Add schedule of events

### ISSUE THREAD

**Issue by arcanistzed** [HacktheHill/track-the-hack#7]
- [x] Add events model to Prisma schema (title, type, host, description, tiktok, room #, resources)
- [x] Write tRPC query to get all events and get a single event
- [x] Use SSR to prefetch the events with tRPC
- [ ] Create component to display events in a list
- [ ] Create component to display a single event with more details 
    - [ ] Link to TikTok
    - [ ] Highlight event room on CRX map
    - [ ] Text description of the event

**Comment by omersayshi** [comment]
Created skeleton for components

**Comment by omersayshi** [comment]
Created tickets for individual components
